"""
FAZENIUM — Localization System
JSON-based i18n for UA, EN, DE
"""
import streamlit as st

# ─── Translation Dictionaries ─────────────────────────

_TRANSLATIONS = {
    "en": {
        # ── App ──
        "app_title": "FAZENIUM",
        "app_subtitle": "EdTech Sandbox for Drug Design",
        "app_tagline": "Powered by Gemma 4 · Made by FAZENA",
        "select_language": "Language",
        "select_difficulty": "Difficulty",
        "difficulty_kid": "Kid (10+)",
        "difficulty_student": "Student",
        "difficulty_expert": "Expert",

        # ── Onboarding ──
        "welcome_title": "Welcome to FAZENIUM",
        "welcome_message": "A new virus in 2026 requires a Fazenium specialist. You've been selected. Choose your path and begin your journey from Junior Researcher to Head of Research Group.",
        "enter_name": "Your Scientist Name",
        "choose_avatar": "Choose Your Avatar",
        "start_journey": "Begin Research",
        "name_placeholder": "Dr. ...",

        # ── Sidebar ──
        "profile_title": "Scientist Profile",
        "rank_label": "Rank",
        "points_label": "Fazena Points",
        "level_select": "Select Module",
        "dashboard": "Lab Hub",

        # ── Ranks ──
        "rank_junior": "Junior Researcher",
        "rank_researcher": "Biochemical Analyst",
        "rank_engineer": "Modeling Engineer",
        "rank_senior": "Senior Scientist",
        "rank_head": "Head of Research Group",

        # ── Levels ──
        "level_1_title": "Code of Life",
        "level_1_desc": "Interactive FASTA/FASTQ parser — decode the language of life",
        "level_2_title": "Molecular Origami",
        "level_2_desc": "RNA secondary structure — fold molecules like origami",
        "level_3_title": "Structure Voyage",
        "level_3_desc": "Dive into 3D protein & RNA structures",
        "level_4_title": "Dual Horizon",
        "level_4_desc": "Compare two 3D structures side by side",
        "level_5_title": "Pattern Master",
        "level_5_desc": "Find structural motifs and patterns",
        "level_6_title": "Active Site Bio",
        "level_6_desc": "Detect and explore binding sites",
        "level_7_title": "Molecular Forge",
        "level_7_desc": "Build molecules with SMILES — your drug workshop",
        "level_8_title": "Clinical Architect",
        "level_8_desc": "Optimize ligands and check drug-likeness",
        "level_9_title": "Dynamic Frontier",
        "level_9_desc": "Docking scores & molecular dynamics simulation",
        "level_10_title": "Global Nexus",
        "level_10_desc": "RAG-powered news feed & database exploration",

        # ── Dashboard ──
        "dash_hero": "Your Research Laboratory",
        "dash_hero_sub": "Choose a module to begin your drug design journey. Each lab offers sandbox freedom — explore, experiment, create.",
        "dash_progress": "Research Progress",
        "dash_modules": "Available Modules",
        "dash_unlocked": "Unlocked",
        "dash_locked": "Locked",

        # ── Gemma Console ──
        "gemma_title": "Gemma AI Assistant",
        "gemma_placeholder": "Ask Gemma anything about drug design...",
        "gemma_send": "Send",
        "gemma_thinking": "Gemma is thinking...",
        "gemma_offline": "Gemma is offline. Responses are simulated.",
        "gemma_loading": "Loading Gemma 4 E2B model...",

        # ── Level 1 ──
        "l1_choose_source": "Choose Your Mission",
        "l1_paste": "Paste Sequence",
        "l1_upload": "Upload FASTA/FASTQ",
        "l1_library": "Threat Library",
        "l1_paste_hint": "Paste a FASTA or FASTQ sequence here...",
        "l1_analyze": "Analyze Sequence",
        "l1_sequence_info": "Sequence Information",
        "l1_length": "Length",
        "l1_gc_content": "GC Content",
        "l1_type": "Type",
        "l1_dna": "DNA",
        "l1_rna": "RNA",
        "l1_protein": "Protein",

        # ── Level 2 ──
        "l2_input_seq": "Enter RNA Sequence",
        "l2_fold": "Predict Folding",
        "l2_structure": "Secondary Structure",
        "l2_pairs": "Base Pairs",
        "l2_free_energy": "Free Energy (approx.)",
        "l2_preview": "Quick Preview",

        # ── Level 3-5 ──
        "l3_pdb_id": "Enter PDB ID",
        "l3_fetch": "Fetch Structure",
        "l3_upload_pdb": "Or Upload PDB File",
        "l3_style": "Render Style",
        "l3_color": "Color Scheme",
        "l3_surface": "Show Surface",
        "l3_spin": "Spin Animation",

        # ── Level 6 ──
        "l6_detect": "Detect Binding Sites",
        "l6_pocket": "Pocket",
        "l6_residues": "Residues",
        "l6_druggability": "Druggability Score",
        "l6_kb_title": "Binding Site Primer",
        "l6_kb_text": "Binding sites (pockets) are specific regions on a protein where a ligand (drug) can bind. They are characterized by their shape, size, and chemical properties like hydrophobicity or charge. Finding the right 'key' for these 'locks' is the essence of drug design.",

        # ── Level 7-8 ──
        "l7_smiles_input": "Enter SMILES",
        "l7_draw": "Render Molecule",
        "l7_properties": "Molecular Properties",
        "l7_mw": "Molecular Weight",
        "l7_logp": "LogP",
        "l7_hbd": "H-Bond Donors",
        "l7_hba": "H-Bond Acceptors",
        "l7_tpsa": "TPSA",
        "l7_lipinski": "Lipinski's Rule of 5",
        "l7_pass": "PASS",
        "l7_fail": "FAIL",
        "l7_fragments": "Fragment Library",

        # ── Level 9 ──
        "l9_run_dock": "Run Docking Simulation",
        "l9_score": "Docking Score",
        "l9_affinity": "Binding Affinity",
        "l9_dynamics": "Run Dynamics",

        # ── Level 10 ──
        "l10_search": "Search",
        "l10_news": "Latest Breakthroughs",
        "l10_export": "Export Research Report",
        "l10_read_more": "Read Full Article",
        "l10_back": "Back to Feed",

        # ── Structural Biology ──
        "sb_rg": "Radius of Gyration (Rg)",
        "sb_rg_desc": "Measures the compactness of a protein. A stable fold usually has a constant Rg.",
        "sb_sasa": "Solvent Accessible Surface Area (SASA)",
        "sb_sasa_desc": "The area of the molecule that is accessible to a solvent. Useful for tracking folding/unfolding.",
        "sb_rmsf": "Root Mean Square Fluctuation (RMSF)",
        "sb_rmsf_desc": "Measures how much each residue moves. High RMSF = flexible loops; Low RMSF = stable core.",
        "sb_rmsd_desc": "Root Mean Square Deviation. Measures the global structural change over time.",
        "sb_hbonds": "Hydrogen Bonds",
        "sb_hbonds_desc": "Tracks the number of H-bonds over time. Essential for structural stability.",
        "sb_energy": "Potential Energy",
        "sb_energy_desc": "The internal energy of the system. Minimization should lead to a stable state.",
        "sb_lesson_title": "Structural Biology Brief",
        "sb_pdb_select": "Select Research Object",
        "sb_obj_dna": "DNA Double Helix (1BNA)",
        "sb_obj_trna": "Transfer RNA (1TRA)",
        "sb_obj_mpro": "SARS-CoV-2 Mpro + Ligand (6LU7)",
        "sb_obj_ribosome": "Bacterial Ribosome Fragment (1UL1)",
        "sb_obj_complex": "CDK2 Protein Complex (1AQ1)",
    },

    "ua": {
        "app_title": "FAZENIUM",
        "app_subtitle": "EdTech Пісочниця для Дизайну Ліків",
        "app_tagline": "На базі Gemma 4 · Створено FAZENA",
        "select_language": "Мова",
        "select_difficulty": "Складність",
        "difficulty_kid": "Дитина (10+)",
        "difficulty_student": "Студент",
        "difficulty_expert": "Експерт",

        "welcome_title": "Ласкаво просимо до FAZENIUM",
        "welcome_message": "Новий вірус 2026 року потребує спеціаліста Fazenium. Вас обрано. Оберіть свій шлях та розпочніть подорож від Молодшого Дослідника до Керівника Дослідницької Групи.",
        "enter_name": "Ім'я Вашого Вченого",
        "choose_avatar": "Оберіть Аватар",
        "start_journey": "Почати Дослідження",
        "name_placeholder": "Д-р ...",

        "profile_title": "Профіль Вченого",
        "rank_label": "Ранг",
        "points_label": "Бали Fazena",
        "level_select": "Обрати Модуль",
        "dashboard": "Центр Лабораторії",

        "rank_junior": "Молодший Дослідник",
        "rank_researcher": "Біохімічний Аналітик",
        "rank_engineer": "Інженер Моделювання",
        "rank_senior": "Старший Науковець",
        "rank_head": "Керівник Дослідницької Групи",

        "level_1_title": "Код Життя",
        "level_1_desc": "Інтерактивний парсер FASTA/FASTQ — розшифруйте мову життя",
        "level_2_title": "Молекулярне Орігамі",
        "level_2_desc": "Вторинна структура РНК — складайте молекули як орігамі",
        "level_3_title": "Структурний Вояж",
        "level_3_desc": "Зануртесь у 3D структури білків та РНК",
        "level_4_title": "Подвійний Горизонт",
        "level_4_desc": "Порівняйте дві 3D структури поруч",
        "level_5_title": "Майстер Патернів",
        "level_5_desc": "Знайдіть структурні мотиви та патерни",
        "level_6_title": "Активний Центр",
        "level_6_desc": "Визначте та дослідіть місця зв'язування",
        "level_7_title": "Молекулярна Кузня",
        "level_7_desc": "Будуйте молекули зі SMILES — ваша лабораторія ліків",
        "level_8_title": "Клінічний Архітектор",
        "level_8_desc": "Оптимізуйте ліганди та перевірте лікоподібність",
        "level_9_title": "Динамічний Рубіж",
        "level_9_desc": "Бали докінгу та симуляція молекулярної динаміки",
        "level_10_title": "Глобальний Нексус",
        "level_10_desc": "Стрічка новин та дослідження баз даних",

        "dash_hero": "Ваша Дослідницька Лабораторія",
        "dash_hero_sub": "Оберіть модуль для початку подорожі. Кожна лабораторія пропонує свободу — досліджуйте, експериментуйте, створюйте.",
        "dash_progress": "Прогрес Дослідження",
        "dash_modules": "Доступні Модулі",
        "dash_unlocked": "Відкрито",
        "dash_locked": "Заблоковано",

        "gemma_title": "Помічник Gemma AI",
        "gemma_placeholder": "Запитайте Gemma про дизайн ліків...",
        "gemma_send": "Надіслати",
        "gemma_thinking": "Gemma думає...",
        "gemma_offline": "Gemma офлайн. Відповіді симульовані.",
        "gemma_loading": "Завантаження моделі Gemma 4 E2B...",

        "l1_choose_source": "Оберіть Місію",
        "l1_paste": "Вставити Послідовність",
        "l1_upload": "Завантажити FASTA/FASTQ",
        "l1_library": "Бібліотека Загроз",
        "l1_paste_hint": "Вставте послідовність FASTA або FASTQ...",
        "l1_analyze": "Аналізувати Послідовність",
        "l1_sequence_info": "Інформація про Послідовність",
        "l1_length": "Довжина",
        "l1_gc_content": "Вміст GC",
        "l1_type": "Тип",
        "l1_dna": "ДНК",
        "l1_rna": "РНК",
        "l1_protein": "Білок",

        "l2_input_seq": "Введіть Послідовність РНК",
        "l2_fold": "Передбачити Фолдинг",
        "l2_structure": "Вторинна Структура",
        "l2_pairs": "Пари Основ",
        "l2_free_energy": "Вільна Енергія (приблизно)",
        "l2_preview": "Швидкий Перегляд",

        "l3_pdb_id": "Введіть PDB ID",
        "l3_fetch": "Завантажити Структуру",
        "l3_upload_pdb": "Або Завантажте PDB Файл",
        "l3_style": "Стиль Рендеру",
        "l3_color": "Кольорова Схема",
        "l3_surface": "Показати Поверхню",
        "l3_spin": "Анімація Обертання",

        "l6_detect": "Знайти Місця Зв'язування",
        "l6_pocket": "Кишеня",
        "l6_residues": "Залишки",
        "l6_druggability": "Оцінка Лікоподібності",
        "l6_kb_title": "База Знань: Сайти Зв'язування",
        "l6_kb_text": "Сайти зв'язування (кишені) — це специфічні ділянки на білку, куди може приєднатися ліганд (ліки). Вони характеризуються формою, розміром та хімічними властивостями. Пошук правильного 'ключа' до цих 'замків' — це основа дизайну ліків.",

        "l7_smiles_input": "Введіть SMILES",
        "l7_draw": "Візуалізувати Молекулу",
        "l7_properties": "Властивості Молекули",
        "l7_mw": "Молекулярна Маса",
        "l7_logp": "LogP",
        "l7_hbd": "Донори Водн. Зв'язків",
        "l7_hba": "Акцептори Водн. Зв'язків",
        "l7_tpsa": "TPSA",
        "l7_lipinski": "Правило П'яти Ліпінського",
        "l7_pass": "ПРОЙДЕНО",
        "l7_fail": "ПРОВАЛЕНО",
        "l7_fragments": "Бібліотека Фрагментів",

        "l9_run_dock": "Запустити Докінг",
        "l9_score": "Бал Докінгу",
        "l9_affinity": "Афінність Зв'язування",
        "l9_dynamics": "Запустити Динаміку",

        "l10_search": "Пошук",
        "l10_news": "Останні Прориви",
        "l10_export": "Експортувати Звіт",
        "l10_read_more": "Читати Повністю",
        "l10_back": "Назад до Стрічки",

        # ── Структурна Біологія ──
        "sb_rg": "Радіус Гірації (Rg)",
        "sb_rg_desc": "Вимірює компактність білка. Стабільна структура зазвичай має постійний Rg.",
        "sb_sasa": "Площа Поверхні, Доступна Розчиннику (SASA)",
        "sb_sasa_desc": "Площа молекули, яка контактує з розчинником. Корисно для відстеження фолдингу.",
        "sb_rmsf": "Середньоквадратична Флуктуація (RMSF)",
        "sb_rmsf_desc": "Вимірює рухливість кожного залишку. Високий RMSF = гнучкі петлі; Низький = стабільне ядро.",
        "sb_rmsd_desc": "Вимірює загальну зміну структури з часом.",
        "sb_hbonds": "Водневі Зв'язки",
        "sb_hbonds_desc": "Кількість Н-зв'язків у часі. Важливо для стабільності структури.",
        "sb_energy": "Потенційна Енергія",
        "sb_energy_desc": "Внутрішня енергія системи. Мінімізація свідчить про стабільність.",
        "sb_lesson_title": "Конспект зі Структурної Біології",
        "sb_pdb_select": "Оберіть Об'єкт Дослідження",
        "sb_obj_dna": "Подвійна спіраль ДНК (1BNA)",
        "sb_obj_trna": "Транспортна РНК (1TRA)",
        "sb_obj_mpro": "SARS-CoV-2 Mpro + Ліганд (6LU7)",
        "sb_obj_ribosome": "Фрагмент бактеріальної рибосоми (1UL1)",
        "sb_obj_complex": "Білковий комплекс CDK2 (1AQ1)",
    },

    "de": {
        "app_title": "FAZENIUM",
        "app_subtitle": "EdTech-Sandbox für Wirkstoffdesign",
        "app_tagline": "Powered by Gemma 4 · Made by FAZENA",
        "select_language": "Sprache",
        "select_difficulty": "Schwierigkeit",
        "difficulty_kid": "Kind (10+)",
        "difficulty_student": "Student",
        "difficulty_expert": "Experte",

        "welcome_title": "Willkommen bei FAZENIUM",
        "welcome_message": "Ein neues Virus im Jahr 2026 erfordert einen FAZENIUM-Spezialisten. Sie wurden ausgewählt. Wählen Sie Ihren Weg und beginnen Sie Ihre Reise vom Nachwuchsforscher zum Forschungsgruppenleiter.",
        "enter_name": "Ihr Wissenschaftlername",
        "choose_avatar": "Wählen Sie Ihren Avatar",
        "start_journey": "Forschung beginnen",
        "name_placeholder": "Dr. ...",

        "profile_title": "Wissenschaftlerprofil",
        "rank_label": "Rang",
        "points_label": "Fazena-Punkte",
        "level_select": "Modul wählen",
        "dashboard": "Labor-Hub",

        "rank_junior": "Nachwuchsforscher",
        "rank_researcher": "Biochemischer Analyst",
        "rank_engineer": "Modellierungsingenieur",
        "rank_senior": "Senior-Wissenschaftler",
        "rank_head": "Forschungsgruppenleiter",

        "level_1_title": "Lebens-Code",
        "level_1_desc": "Interaktiver FASTA/FASTQ-Parser — entschlüsseln Sie die Sprache des Lebens",
        "level_2_title": "Molekulares Origami",
        "level_2_desc": "RNA-Sekundärstruktur — falten Sie Moleküle wie Origami",
        "level_3_title": "Struktur-Voyage",
        "level_3_desc": "Tauchen Sie ein in 3D-Protein- und RNA-Strukturen",
        "level_4_title": "Dualer Horizont",
        "level_4_desc": "Vergleichen Sie zwei 3D-Strukturen nebeneinander",
        "level_5_title": "Muster-Meister",
        "level_5_desc": "Finden Sie strukturelle Motive und Muster",
        "level_6_title": "Aktives Zentrum",
        "level_6_desc": "Erkennen und erforschen Sie Bindungsstellen",
        "level_7_title": "Molekulare Schmiede",
        "level_7_desc": "Bauen Sie Moleküle mit SMILES — Ihre Wirkstoff-Werkstatt",
        "level_8_title": "Klinischer Architekt",
        "level_8_desc": "Optimieren Sie Liganden und prüfen Sie Arzneimittelähnlichkeit",
        "level_9_title": "Dynamische Grenze",
        "level_9_desc": "Docking-Scores und Molekulardynamik-Simulation",
        "level_10_title": "Globaler Nexus",
        "level_10_desc": "KI-gestützter News-Feed und Datenbank-Erkundung",

        "dash_hero": "Ihr Forschungslabor",
        "dash_hero_sub": "Wählen Sie ein Modul, um Ihre Reise zu beginnen. Jedes Labor bietet Sandbox-Freiheit — erkunden, experimentieren, erschaffen.",
        "dash_progress": "Forschungsfortschritt",
        "dash_modules": "Verfügbare Module",
        "dash_unlocked": "Freigeschaltet",
        "dash_locked": "Gesperrt",

        "gemma_title": "Gemma KI-Assistent",
        "gemma_placeholder": "Fragen Sie Gemma zum Wirkstoffdesign...",
        "gemma_send": "Senden",
        "gemma_thinking": "Gemma denkt nach...",
        "gemma_offline": "Gemma ist offline. Antworten werden simuliert.",
        "gemma_loading": "Lade Gemma 4 E2B Modell...",

        "l1_choose_source": "Wählen Sie Ihre Mission",
        "l1_paste": "Sequenz einfügen",
        "l1_upload": "FASTA/FASTQ hochladen",
        "l1_library": "Bedrohungsbibliothek",
        "l1_paste_hint": "Fügen Sie eine FASTA- oder FASTQ-Sequenz ein...",
        "l1_analyze": "Sequenz analysieren",
        "l1_sequence_info": "Sequenzinformationen",
        "l1_length": "Länge",
        "l1_gc_content": "GC-Gehalt",
        "l1_type": "Typ",
        "l1_dna": "DNA",
        "l1_rna": "RNA",
        "l1_protein": "Protein",

        "l2_input_seq": "RNA-Sequenz eingeben",
        "l2_fold": "Faltung vorhersagen",
        "l2_structure": "Sekundärstruktur",
        "l2_pairs": "Basenpaare",
        "l2_free_energy": "Freie Energie (ungefähr)",
        "l2_preview": "Schnellvorschau",

        "l3_pdb_id": "PDB-ID eingeben",
        "l3_fetch": "Struktur abrufen",
        "l3_upload_pdb": "Oder PDB-Datei hochladen",
        "l3_style": "Render-Stil",
        "l3_color": "Farbschema",
        "l3_surface": "Oberfläche anzeigen",

        "l6_detect": "Bindungsstellen erkennen",
        "l6_pocket": "Tasche",
        "l6_residues": "Reste",
        "l6_druggability": "Druggability-Score",

        "l7_smiles_input": "SMILES eingeben",
        "l7_draw": "Molekül rendern",
        "l7_properties": "Moleküleigenschaften",
        "l7_mw": "Molekulargewicht",
        "l7_logp": "LogP",
        "l7_hbd": "H-Brücken-Donoren",
        "l7_hba": "H-Brücken-Akzeptoren",
        "l7_tpsa": "TPSA",
        "l7_lipinski": "Lipinskis Fünferregel",
        "l7_pass": "BESTANDEN",
        "l7_fail": "DURCHGEFALLEN",
        "l7_fragments": "Fragment-Bibliothek",

        "l9_run_dock": "Docking starten",
        "l9_score": "Docking-Score",
        "l9_affinity": "Bindungsaffinität",
        "l9_dynamics": "Dynamik starten",

        "l10_search": "Suche",
        "l10_news": "Neueste Durchbrüche",
        "l10_export": "Forschungsbericht exportieren",
    },
}


def t(key: str) -> str:
    """Translate key using the current session language."""
    lang = st.session_state.get("language", "en")
    translations = _TRANSLATIONS.get(lang, _TRANSLATIONS["en"])
    return translations.get(key, _TRANSLATIONS["en"].get(key, key))
